### ISSUE TITLE
TypeError when running under nginx

### ISSUE THREAD

**Issue by 4x4falcon** [TimSC/pycrocosm#10]
Following requests generate type errors when operating under nginx server.
http://api.freestreetmap.org:8010/api/0.6/way/1000002429454
http://api.freestreetmap.org:8010/api/0.6/node/1000595144708
http://api.freestreetmap.org:8010/api/0.6/relation/1000000155435

Does not occur for changeset requests.

From debug screen:

Exception Value:  __init__() takes exactly 2 arguments (3 given)
Exception Location: ./elements/views.py in element, line 89

This error does not occur running django server ie python manage.py runserver

**Comment by TimSC** [comment]
The most likely cause is that cppo5m is not up to date. Try clearing any intermediate build files, update to the latest cppo5m and recompile.

(The error is in "enc = pgmap.PyOsmXmlEncode(sio, common.xmlAttribs)" in elements/views.py which needs to match the PyOsmXmlEncode function in https://github.com/TimSC/pgmap/blob/master/pgmap.i )

**Comment by 4x4falcon** [comment]
Complete rebuild of cppo5m, pgmap and pycrocosm to latest on github.

Resolved.

Problem occurs when running

sudo python setup.py install

in the virtualenv but running nginx outside of the virtualenv

**Comment by 4x4falcon** [comment]
Resolved

**Comment by TimSC** [comment]
I'm still trying to get my head around virtualenv. You seem to be able to configure it for a live website by setting the home variable in pycrocosm.ini
