### ISSUE TITLE
Changeset display does not show legacy users.

### ISSUE THREAD

**Issue by 4x4falcon** [TimSC/pycrocosm#11]
At:

http://api.freestreetmap.org:8010/api/0.6/changesets?display_name=

or

http://api.freestreetmap.org:8010/api/0.6/changesets?user=

will not show a user's changesets unless the user name is in auth_users

The lookup for this should check in database table migrateusers_legacyaccount as well for username and uid.

**Comment by TimSC** [comment]
This should be fixed. Also, any uid may be used, not just those in the Users and LegacyAccount tables.
