### ISSUE TITLE
minlat maxlat minlon maxlon in xapi queries

### ISSUE THREAD

**Issue by 4x4falcon** [TimSC/pycrocosm#26]
With the following query:

http://fosm.org/api/0.6/map?bbox=-164.75,-79.75,-164.50,-80.00

the minlat and maxlat are incorrect in the returned xml.

minlat should be -80.00 and maxlat should be -79.75

Same occurs with minlon and maxlon if they are reversed in the query.

Possibly should be a check that the returned xml is in the correct order rather than just accepting what is in the query.

Maybe this should generate an error as the bbox should be left,bottom,right,top whereas the above is left,top,right,bottom

Not an urgent issue as it's just something I came across.

**Comment by TimSC** [comment]
This is a quick one for a change! Fixed in ae65eea
