### ISSUE TITLE
Claim existing fosm usernames, with appropriate uid

### ISSUE THREAD

**Issue by TimSC** [TimSC/pycrocosm#8]
There should be a way to claim existing fosm usernames, with appropriate uid.

**Comment by 4x4falcon** [comment]
I have all the usernames and uid in a xml file.  Like this:

<?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' generator='FreeOSM API 0.6'>
<user display_name='Rosscoe' id='4467' email='info@4x4falcon.com' account_created='2010-09-27T23:50:17Z'>
    <description/>
    <contributor_terms pd='false' agreed='false'/>
    <home lat='0.0' lon='0.0' zoom='3'/>
    <languages>
      <lang>en</lang>
    </languages>
  </user>
</osm>

Only one user name but shown but the complete file is the same format.

There is a function in the user.m script on fosm.org that can output this.  I wrote a separate function which could be modified to output as a csv file if that is easier to import.

**Comment by TimSC** [comment]
I have dumped the hashed passwords from fosm. I hoped that people could actually sign into the pycrocosm site to verify their identity.

**Comment by 4x4falcon** [comment]
When we get to the point of changing over the server this will probably happen.  Will the hashed passwords work in the new database?  I had not included them as I did not think I would work.

**Comment by TimSC** [comment]
You are right, django and fosm use completely different mechanisms to hash the password.

I was thinking of having two separate forms: register new user, and claim fosm user. The claim fosm user would check form input against a custom table, then create a real django user if the password matched.

**Comment by 4x4falcon** [comment]
Sounds good.  I can modify my script on fosm.org to add the password into the xml file.

**Comment by 4x4falcon** [comment]
I have osm xml output as above for all users with password only change is in the user node to

<user display_name='Rosscoe' id='4467' email='info@4x4falcon.com' sha256pw='' account_created='2010-09-27T23:50:17Z'>

Where sha256pw contains the password hash

**Comment by TimSC** [comment]
@4x4falcon I've added the ability to import legacy account data and for it to check the username/password. I've not done the account creation yet. Because I modified to django schema, you will need to run "python manage.py migrate" to update your database.

Then to import account info: python manage.py importlegacyaccounts legacy.xml

Password check form: http://localhost:8000/migrateusers/ (or whatever host you really use)

**Comment by 4x4falcon** [comment]
@TimSC there's no additional change in the settings.py.template but I sorted it by adding migrateusers to the settings.py

All users imported ok.

If a user goes to http://api.freestreetmap.org:8000/migrateusers/ and the password is ok does this then update the auth_users table in the db_settings database?

**Comment by TimSC** [comment]
This should now be working (after 760ed95).
